name: DevSecOps Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run App Tests
        run: echo "Pretend tests here"

      - name: Scan with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'node:14'

      - name: Secret Scanner
        uses: zricethezav/gitleaks-action@v2.0.0

      - name: Done
        run: echo "DevSecOps check complete ✅"
